# Generated by Django 5.0.6 on 2024-05-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_type',
            field=models.CharField(choices=[('suite', 'Suite'), ('junior', 'Junior Suite'), ('deluxe', 'Deluxe Room'), ('standard', 'Standard Room'), ('villa', 'Villa')], max_length=10),
        ),
    ]
